AWSTemplateFormatVersion: 2010-09-09

Parameters:

  OGSImageId:
    Type: List<AWS::EC2::Image::Id>
    Description: you can coose your Image ID
  OGSInstanceId:
    Type: AWS::EC2::Instance::Id
    Description: You can choose Your Instance ID
  OGSKeyValue:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Check with your exsting KeyPair.

Resources:
  MYEc2Mechine:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref OGSImageId     #ohio
      InstanceType: !Ref OGSInstanceId
      KeyName: !Ref OGSKeyValue
      Tags:
        -
          Key: Name
          Value: MyEC2_Server
        -
          Key: Project
          Value: Dev Environment



#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html >>> link for examle script
